blossom:
  rpc:
    serviceAddress: 127.0.0.1
    servicePort: 8080
    registerAddress: localhost:8848
    registerName: nacos

server:
  port: 9999

nacos:
  discovery:
    register:
      ip: 123.249.111.175
      port: 8848